/* users 테이블 생성 */
CREATE TABLE users (
	id SERIAL PRIMARY KEY, 
	name VARCHAR(100) NOT NULL, 
	email VARCHAR(100) UNIQUE NOT NULL, 
	password VARCHAR(255),

	provider VARCHAR(50) NOT NULL DEFAULT 'local',
	provider_id VARCHAR(255),

	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

	UNIQUE (provider, provider_id)
);

/* products 테이블 생성 */
CREATE TABLE products (
	id SERIAL PRIMARY KEY,
	user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	name VARCHAR(10) NOT NULL,
	description TEXT NOT NULL CHECK (char_length(description) >= 10),
	price INTEGER NOT NULL CHECK (price >= 0),

	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE product_images (
	id SERIAL PRIMARY KEY,
	product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
	image_url VARCHAR(255) NOT NULL,
	display_order SMALLINT DEFAULT 0
);

CREATE TABLE product_likes (
	user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,

	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

	PRIMARY KEY (user_id, product_id)
);

CREATE TABLE tags (
	id SERIAL PRIMARY KEY,
	name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE product_tags (
	product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
	tag_id INTEGER NOT NULL REFERENCES tags(id) ON DELETE CASCADE,

	PRIMARY KEY (product_id, tag_id)
);

/* posts 테이블 생성 */
CREATE TABLE posts (
	id SERIAL PRIMARY KEY,
	user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	title VARCHAR(100) NOT NULL,
	content TEXT NOT NULL,

	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE post_images (
	id SERIAL PRIMARY KEY,
	post_id INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
	image_url VARCHAR(255) NOT NULL,
	display_order SMALLINT DEFAULT 0
);

CREATE TABLE post_likes (
	user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	post_id INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE,

	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

	PRIMARY KEY (user_id, post_id)
);

/* comments 테이블 생성 */
CREATE TABLE comments (
	id SERIAL PRIMARY kEY,
	user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	product_id INTEGER REFERENCES products(id) ON DELETE CASCADE,
	post_id INTEGER REFERENCES posts(id) ON DELETE CASCADE,
	content TEXT NOT NULL CHECK (char_length(content) <= 250),

	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT comment_target_check CHECK ((product_id IS NOT NULL AND post_id IS NULL) OR (post_id IS NOT NULL AND product_id IS NULL))
);
